import { db } from "./db";
import { reconciliationRules } from "@shared/schema";

export async function seedDefaultRules() {
  const existing = await db.select().from(reconciliationRules);
  if (existing.length > 0) return;

  const defaultRules = [
    {
      ruleId: "IC-R1",
      name: "Invoice/Reference Match",
      ruleType: "invoice_match",
      matchType: "1:1",
      priority: 1,
      dateTolerance: null,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "real_match",
      classification: "AUTO_MATCH",
      active: true,
      description: "Invoice/Reference number extracted from narration matches exactly. Highest confidence — requires regex extraction from narration.",
      params: null,
    },
    {
      ruleId: "IC-R2",
      name: "Exact Date + Exact Amount",
      ruleType: "exact_match",
      matchType: "1:1",
      priority: 2,
      dateTolerance: 0,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "real_match",
      classification: "AUTO_MATCH",
      active: true,
      description: "Standard IC matching rule — exact date and exact amount match between counterparties (1:1).",
      params: null,
    },
    {
      ruleId: "IC-R3",
      name: "Amount + Date within tolerance (±0-5 days)",
      ruleType: "date_range_match",
      matchType: "1:1",
      priority: 3,
      dateTolerance: 5,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "real_match",
      classification: "AUTO_MATCH",
      active: true,
      description: "Handles posting delays — exact amount match with date tolerance of ±5 days.",
      params: null,
    },
    {
      ruleId: "IC-R4",
      name: "Aggregation Match on same date",
      ruleType: "exact_aggregation",
      matchType: "1:M",
      priority: 4,
      dateTolerance: 0,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "real_match",
      classification: "AUTO_MATCH",
      active: true,
      description: "Useful when invoices consolidated — sum of multiple transactions equals counter entry on same date.",
      params: null,
    },
    {
      ruleId: "IC-R5",
      name: "Aggregation Match + Date tolerance (±0-5 days)",
      ruleType: "date_range_aggregation",
      matchType: "1:M",
      priority: 5,
      dateTolerance: 5,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "real_match",
      classification: "AUTO_MATCH",
      active: true,
      description: "Aggregation match with date tolerance — sum of transactions equals counter entry within ±5 days.",
      params: null,
    },
    {
      ruleId: "IC-R6",
      name: "Reversal Transactions (±0-5 days)",
      ruleType: "reversal_match",
      matchType: "1:M",
      priority: 6,
      dateTolerance: 5,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "real_match",
      classification: "REVERSAL",
      active: true,
      description: "Reversal of transactions in same entity books with counter party getting cancelled off. Positives=Negatives within ±5 days.",
      params: null,
    },
    {
      ruleId: "IC-R7",
      name: "Exact Amount match only",
      ruleType: "amount_only_match",
      matchType: "1:1",
      priority: 7,
      dateTolerance: null,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "probable_match",
      classification: "REVIEW_MATCH",
      active: true,
      description: "Probable match — exact amount match with dates ignored. Needs human review.",
      params: null,
    },
    {
      ruleId: "IC-R8",
      name: "Narration fuzzy match",
      ruleType: "fuzzy_narration_match",
      matchType: "1:1",
      priority: 8,
      dateTolerance: null,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "probable_match",
      classification: "REVIEW_MATCH",
      active: true,
      description: "Narration fuzzy match (similarity > 80%, if narration is more than 20 characters). Uses fuzzy matching.",
      params: JSON.stringify({ fuzzyThreshold: 0.8, minNarrationLength: 20 }),
    },
    {
      ruleId: "IC-R9",
      name: "Aggregated Amount match only",
      ruleType: "amount_only_aggregation",
      matchType: "1:M",
      priority: 9,
      dateTolerance: null,
      amountTolerance: 5,
      amountTolerancePct: 0,
      confidence: "probable_match",
      classification: "REVIEW_MATCH",
      active: true,
      description: "Aggregated amount match with no date constraint. Higher false positive risk — needs review.",
      params: null,
    },
    {
      ruleId: "IC-R10",
      name: "Combined Scoring",
      ruleType: "combined_scoring",
      matchType: "1:M",
      priority: 10,
      dateTolerance: null,
      amountTolerance: 0,
      amountTolerancePct: 0.05,
      confidence: "suggestion",
      classification: "SUGGESTED_MATCH",
      active: true,
      description: "Combined scoring — amount + date proximity + narration similarity (if narration > 20 chars). Lowest confidence.",
      params: JSON.stringify({ scoreThreshold: 50, amountWeight: 50, dateWeight: 30, narrationWeight: 20 }),
    },
  ];

  await db.insert(reconciliationRules).values(defaultRules);
  console.log("Seeded 10 default reconciliation rules (IC-R1 to IC-R10)");
}
